Comprehensive automatic safety checks

diff --git a/code-checker b/code-checker
--- a/code-checker
+++ b/code-checker
@@ -1,33 +1,77 @@
 #!/bin/bash
 
 set -e
+shopt -s nullglob # Don't iterate if there are no elements to do so
 
 EXIT_CODE=0
 
+# Assert only '#include <...>' and not '#include "..."'
 if grep -Rn ./src -e '#include "'
 then
-  echo "Please always use #include <...> starting from ./src (manually included) to preserve links if we move files"
+  echo -e "Please always use #include <...> starting from ./src (manually included) to preserve links if we move files\n\n\n"
   EXIT_CODE=1
 fi
 
-for file in $(find ./src -iname '*.hpp')
+# Assert #include guards & namespaces
+for dir in ./src/*/
 do
-  if [[ "$(head -n1 ${file})" != '#ifndef'* ]]
-  then
-    echo "Please add #include guards to ${file}"
-    EXIT_CODE=1
-  fi
-done
+  dirname=$(echo ${dir::${#dir}-1} | rev | cut -d/ -f1 | rev)
+  DIRUPPER=$(echo ${dirname} | tr '[:lower:]' '[:upper:]')
 
-for file in $(find ./src/display -type f)
-do
-  if [ "$(sed '3q;d' ${file})" != '#include <util/options.hpp>' ] || [ "$(sed '4q;d' ${file})" != '#if DISPLAY_ON' ]
+  # Make sure folder name is lowercase
+  if [ "${dirname}" != "$(echo ${dirname} | tr '[:upper:]' '[:lower:]')" ]
   then
-    echo -e "Please conditionally compile all ./src/display files with \"#if DISPLAY_ON\" \
-          (and ofc \"#include <util/options.hpp>\") at lines 3-4; \
-          compiling a display is useless on Nao and wastes a ton of memory"
+    echo -e "Please lowercase folder ${dir}\n\n\n"
     EXIT_CODE=1
   fi
+
+  # Make sure this folder is known to src/options.hpp
+  if ! grep -qw "_${DIRUPPER}_ENABLED" ./src/options.hpp
+  then
+    echo -e "Please add _${DIRUPPER}_ENABLED support to ./src/options.hpp\n\n\n"
+    EXIT_CODE=1
+  fi
+
+  for file in ${dir}*.hpp
+  do
+    filename=$(echo ${file} | rev | cut -d/ -f1 | rev)
+    FILEUPPER=$(echo ${filename} | tr '[:lower:]' '[:upper:]' | tr '.' '_')
+
+    # Include guards at the top
+    if [ "$(head -n5 ${file} | tr -d '\n')" != "#include <options.hpp>#if ${DIRUPPER}_ENABLED#ifndef ${DIRUPPER}_${FILEUPPER}_#define ${DIRUPPER}_${FILEUPPER}_" ]
+    then
+      echo -e "Missing or unsafe #include guards at the top of ${file}; please use the following:\n\n#include <options.hpp>\n#if ${DIRUPPER}_ENABLED\n#ifndef ${DIRUPPER}_${FILEUPPER}_\n#define ${DIRUPPER}_${FILEUPPER}_\n\n[your #includes]\n\nnamespace ${dirname} {\n\n\n"
+      EXIT_CODE=1
+    fi
+
+    # Ending those guards & namespace
+    if [ "$(tail -n6 ${file} | tr -d '\n')" != "} // namespace ${dirname}#endif // ${DIRUPPER}_${FILEUPPER}_#endif // ${DIRUPPER}_ENABLED" ]
+    then
+      echo -e "Missing or unsafe #include guards and namespace at the bottom of ${file}; please use the following:\n\n} // namespace ${dirname}\n\n#endif // ${DIRUPPER}_${FILEUPPER}_\n\n#endif // ${DIRUPPER}_ENABLED\n\n\n"
+      EXIT_CODE=1
+    fi
+
+    # Ending newline
+    if [ ! -z "$(tail -c1 ${file})" ]
+    then
+      echo -e "Missing newline at the end of ${file}\n\n\n"
+      EXIT_CODE=1
+    fi
+
+    # No #includes inside namespace
+    LAST_NAMESPACE=$(grep -n '^namespace' ${file} | tail -n1 | cut -d: -f1)
+    if [ -z "${LAST_NAMESPACE}" ]
+    then
+      echo -e "Please use \`namespace ${dirname}\` in ${file}\n\n\n"
+    else
+      if [ "$(grep -n '#include' ${file} | tail -n1 | cut -d: -f1)" -gt "${LAST_NAMESPACE}" ]
+      then
+        echo -e "Please make sure all headers are #include'd before opening a namespace in ${file}\n\n\n"
+        EXIT_CODE=1
+      fi
+    fi
+
+  done
 done
 
 if [ ${EXIT_CODE} -eq 0 ]
